import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/NextUiComp";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="md:w-[400px]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white-300  dark:bg-black dark:text-white `}>
        <Providers>
          {" "}
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
